on: [push]

jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest Apache JMeter
        run: |
          JMETER_VERSION=5.6.3
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
          tar -xzf apache-jmeter-$JMETER_VERSION.tgz
          sudo mv apache-jmeter-$JMETER_VERSION /opt/jmeter
          echo "export PATH=$PATH:/opt/jmeter/bin" >> $GITHUB_ENV

      - name: Create reports directory
        run: mkdir -p reports/html

      - name: Run JMeter Tests
        run: |
          /opt/jmeter/bin/jmeter -n -t ./AssistantApi.jmx -l result.jtl -e -o ./reports/html/

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: result.jtl
          if-no-files-found: error

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-reports
          path: reports
          if-no-files-found: error
          
